global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'flask-service'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'flask-prom-grafana-devops.default.svc.cluster.local:80'

