apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels: { app: grafana }
  template:
    metadata:
      labels: { app: grafana }
    spec:
      containers:
        - name: grafana
          image: grafana/grafana-oss:latest
          env:
            - { name: GF_AUTH_ANONYMOUS_ENABLED,  value: "true" }
            - { name: GF_AUTH_ANONYMOUS_ORG_ROLE, value: "Viewer" }
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: ds
              mountPath: /etc/grafana/provisioning/datasources
            - name: provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: ds
          configMap:
            name: grafana-datasources
        - name: provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboards
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector: { app: grafana }
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
