apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-prom-grafana-devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-prom-grafana-devops
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
