name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build-smoketest-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (via GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build locally first for smoke test (no push)
      - name: Build image (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ghcr.io/${{ env.OWNER }}/flask-prom-grafana-devops:ci

      - name: Smoke test container
        run: |
          docker run -d --rm -p 8000:8000 --name app ghcr.io/${OWNER}/flask-prom-grafana-devops:ci
          for i in {1..30}; do
            if curl -fsS http://localhost:8000/healthz >/dev/null; then echo "healthy"; break; fi
            sleep 1
          done
          curl -fsS http://localhost:8000/metrics | head -n 5
          docker rm -f app

      # Build again and push (uses cache, so it’s quick)
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/flask-prom-grafana-devops:latest
            ghcr.io/${{ env.OWNER }}/flask-prom-grafana-devops:${{ github.sha }}
